version: '3'
services:
  # The Application
  app:
    build: .
    volumes:
      - .:/usr/src/app    
    container_name: sit323-737-2023-t1-prac5p_app
    restart: always
    ports:
        - 8081:8080
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
   

    